name: Release Version

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Build frontend
        run: |
          chmod +x prebuild.sh
          ./prebuild.sh
        
      - name: Build binaries
        run: |
          # Create dist directory
          mkdir -p dist

          # Build home-control-center
          echo "Building home-control-center"
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/home-control-center-linux-amd64 ./cmd/
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o dist/home-control-center-linux-arm64 ./cmd/
          GOOS=linux GOARCH=arm GOARM=6 go build -ldflags="-s -w" -o dist/home-control-center-linux-arm6 ./cmd/
          GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="-s -w" -o dist/home-control-center-linux-arm7 ./cmd/
          
      - name: Create checksums
        run: |
          cd dist
          sha256sum * > checksums.txt
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: Release ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            dist/home-control-center-*
            dist/checksums.txt
          body: |
            ## What's Changed
            
            Release ${{ steps.version.outputs.VERSION }} of Home Control Center
            
            ### Download the appropriate binary for your system:
            - **Linux x64**: `home-control-center-linux-amd64`
            - **Linux ARM64**: `home-control-center-linux-arm64` (Pi 4, Pi 5, newer 64-bit boards)
            - **Linux ARMv6**: `home-control-center-linux-arm6` (Pi Zero, Pi 1, older boards)
            - **Linux ARMv7**: `home-control-center-linux-arm7` (Pi 2, Pi 3, most common 32-bit ARM)
            
            Verify downloads with `checksums.txt`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}